name: pjsip for Windows with ffmpeg and openssl
on:
  push: 
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  swig-url: 'https://github.com/pjsip/third_party_libs/raw/main/swigwin-4.1.1.zip'
  
jobs:
  default:     
    runs-on: windows-latest 
    steps: 
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.140", `
        "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
        "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
    - name: get swig
      run: Invoke-WebRequest -Uri ${{ env.swig-url }}  -OutFile ".\swigwin.zip"
      shell: powershell
    - name: expand swig
      run: |
        Expand-Archive -LiteralPath .\swigwin.zip -DestinationPath .; pwd
        cd swigwin-4.1.1
        Add-Content ..\swig_path.txt $pwd.Path
      shell: powershell 
    - name: config site
      run: cp ${{github.workspace}}\x86\config_site.h ${{github.workspace}}\pjsip\pjlib\include\pj\
      shell: powershell
    - name: MSBuild
      run: | 
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild ${{github.workspace}}\pjsip\pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release-Dynamic /p:Platform=win32
      shell: cmd
    - name: replace  
      uses: Nambers/ReplaceStringInFile@v1.3
      with: 
        path: ${{ github.workspace }}/pjsip/pjsip-apps/build/swig_csharp_pjsua2.vcxproj
        oldString: ProjectReference Include
        oldStringWin: ProjectReference Include
        newString: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        newStringWin: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        showFileContent: true
    - name: build csharp swig
      run: |
        set /P SWIG_PATH=<swig_path.txt
        set PATH=%PATH%;%SWIG_PATH% 
        cd pjsip/pjsip-apps/build 
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" 
        msbuild swig_csharp_pjsua2.vcxproj /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: pjsua2.dll
        path: ${{ github.workspace }}/pjsip/pjsip-apps/src/swig/csharp/

  with-ssl:     
    runs-on: windows-latest 
    
    steps: 
    - uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.140", `
        "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
        "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
    - name: get swig
      run: Invoke-WebRequest -Uri ${{ env.swig-url }}  -OutFile ".\swigwin.zip"
      shell: powershell
    - name: expand swig
      run: |
        Expand-Archive -LiteralPath .\swigwin.zip -DestinationPath .; pwd
        cd swigwin-4.1.1
        Add-Content ..\swig_path.txt $pwd.Path
      shell: powershell
    - name: get openssl
      run: Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/openssl-1.1.1s-win.zip" -OutFile ".\openssl.zip"
      shell: powershell
    - name: expand openssl
      run: |
        Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .; pwd
        cd openssl_build
        Add-Content ..\openssl_dir.txt $pwd.Path
      shell: powershell
    - name: config site
      run:  cp ${{github.workspace}}\ssl-x86\config_site.h ${{github.workspace}}\pjsip\pjlib\include\pj\
      shell: powershell 
    - name: MSBuild
      working-directory: .
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include
        set LIB=%LIB%;%OPENSSL_DIR%\lib
        msbuild ${{github.workspace}}\pjsip\pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release-Dynamic /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - name: replace  
      uses: Nambers/ReplaceStringInFile@v1.3
      with: 
        path: ${{ github.workspace }}/pjsip/pjsip-apps/build/swig_csharp_pjsua2.vcxproj
        oldString: ProjectReference Include
        oldStringWin: ProjectReference Include
        newString: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        newStringWin: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        showFileContent: true
    - name: build csharp swig
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        set /P SWIG_PATH=<swig_path.txt
        set PATH=%PATH%;%SWIG_PATH%  
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include
        set LIB=%LIB%;%OPENSSL_DIR%\lib
        cd pjsip/pjsip-apps/build 
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" 
        msbuild swig_csharp_pjsua2.vcxproj /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: pjsua2.dll
        path: ${{ github.workspace }}/pjsip/pjsip-apps/src/swig/csharp
        
  with-ffmpeg:      
    runs-on: windows-latest 
    
    steps: 
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.140", `
        "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
          "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
    - name: get swig
      run: Invoke-WebRequest -Uri ${{ env.swig-url }}  -OutFile ".\swigwin.zip"
      shell: powershell
    - name: expand swig
      run: |
        Expand-Archive -LiteralPath .\swigwin.zip -DestinationPath .; pwd
        cd swigwin-4.1.1
        Add-Content ..\swig_path.txt $pwd.Path
      shell: powershell  
    - name: get ffmpeg
      run: Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/ffmpeg-5.1.2-win.zip" -Outfile "ffmpeg.zip"
      shell: powershell
    - name: expand ffmpeg
      run: |
        Expand-Archive -LiteralPath .\ffmpeg.zip -DestinationPath .; pwd
        cd ffmpeg_build
        Add-Content ..\ffmpeg_dir.txt $pwd.Path
      shell: powershell
    - name: check ffmpeg folder
      run: |
        set /P FFMPEG_DIR=<ffmpeg_dir.txt
        dir "%FFMPEG_DIR%\include"
        dir "%FFMPEG_DIR%\lib"
      shell: cmd
    - name: get sdl
      run: Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-VC.zip" -Outfile ".\sdl.zip"
      shell: powershell
    - name: expand sdl
      run: |
        Expand-Archive -LiteralPath .\sdl.zip -DestinationPath .; pwd
        cd SDL2-2.26.2
        Add-Content ..\sdl_dir.txt $pwd.Path
      shell: powershell
    - name: check sdl folder
      run: |
        set /P SDL_DIR=<sdl_dir.txt
        dir "%SDL_DIR%\include"
        dir "%SDL_DIR%\lib\x86"
      shell: cmd
    
    - name: config site
      run: cp ffmpeg\config_site.h pjsip\pjlib\include\pj\
      shell: powershell 
    - name: MSBuild
      working-directory: .
      run: |
        set /P FFMPEG_DIR=<ffmpeg_dir.txt        
        set /P SDL_DIR=<sdl_dir.txt
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%FFMPEG_DIR%\include;%SDL_DIR%\include
        set LIB=%LIB%;%FFMPEG_DIR%\lib;%SDL_DIR%\lib\x86
        msbuild pjsip/pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release-Dynamic /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - name: replace  
      uses: Nambers/ReplaceStringInFile@v1.3
      with: 
        path: ${{ github.workspace }}/pjsip/pjsip-apps/build/swig_csharp_pjsua2.vcxproj
        oldString: ProjectReference Include
        oldStringWin: ProjectReference Include
        newString: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        newStringWin: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        showFileContent: true
    - name: build csharp swig
      run: |
        set /P SWIG_PATH=<swig_path.txt
        set PATH=%PATH%;%SWIG_PATH% 
        cd pjsip/pjsip-apps/build
        msbuild swig_csharp_pjsua2.vcxproj /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: pjsua2.dll
        path: ${{ github.workspace }}/pjsip/pjsip-apps/src/swig/csharp
    
  with-ffmpeg-ssl:       
    runs-on: windows-latest 
    
    steps: 
    - uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
      shell: powershell
      run: |
        $VS_BTOOLS_EXE="vs_buildtools.exe"
        $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
        Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
        Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
        "--add", "Microsoft.VisualStudio.Component.VC.140", `
        "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
        "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
    - name: get swig
      run: Invoke-WebRequest -Uri ${{ env.swig-url }}  -OutFile ".\swigwin.zip"
      shell: powershell
    - name: expand swig
      run: |
        Expand-Archive -LiteralPath .\swigwin.zip -DestinationPath .; pwd
        cd swigwin-4.1.1
        Add-Content ..\swig_path.txt $pwd.Path
      shell: powershell
    - name: get openssl
      run: Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/openssl-1.1.1s-win.zip" -OutFile ".\openssl.zip"
      shell: powershell
    - name: expand openssl
      run: |
        Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .;
        cd openssl_build
        Add-Content ..\openssl_dir.txt $pwd.Path
        shell: powershell
    - name: get ffmpeg
      run: Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/ffmpeg-5.1.2-win.zip" -Outfile "ffmpeg.zip"
      shell: powershell
    - name: expand ffmpeg
      run: |
        Expand-Archive -LiteralPath .\ffmpeg.zip -DestinationPath .; pwd
        cd ffmpeg_build
        Add-Content ..\ffmpeg_dir.txt $pwd.Path
      shell: powershell
    - name: check ffmpeg folder
      run: |
        set /P FFMPEG_DIR=<ffmpeg_dir.txt
        dir "%FFMPEG_DIR%\include"
        dir "%FFMPEG_DIR%\lib"
      shell: cmd
    - name: get sdl
      run: Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.26.2/SDL2-devel-2.26.2-VC.zip" -Outfile ".\sdl.zip"
      shell: powershell
    - name: expand sdl
      run: |
        Expand-Archive -LiteralPath .\sdl.zip -DestinationPath .\sdl_build\; pwd
        cd sdl_build\SDL2-2.26.2
        Add-Content ..\..\sdl_dir.txt $pwd.Path
      shell: powershell
    - name: check sdl folder
      run: |
        set /P SDL_DIR=<sdl_dir.txt
        dir "%SDL_DIR%\include"
        dir "%SDL_DIR%\lib\x86"
      shell: cmd 
    - name: config site
      run: cp ffmpeg-ssl\config_site.h pjsip\pjlib\include\pj\
      shell: powershell 
    - name: MSBuild
      working-directory: .
      run: |
        set /P FFMPEG_DIR=<ffmpeg_dir.txt        
        set /P SDL_DIR=<sdl_dir.txt
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%FFMPEG_DIR%\include;%SDL_DIR%\include;%OPENSSL_DIR%\include
        set LIB=%LIB%;%FFMPEG_DIR%\lib;%SDL_DIR%\lib\x86;%LIB%;%OPENSSL_DIR%\lib
        msbuild pjsip\pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release-Dynamic /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - name: replace 
      uses: Nambers/ReplaceStringInFile@v1.3
      with: 
        path: ${{ github.workspace }}/pjsip/pjsip-apps/build/swig_csharp_pjsua2.vcxproj
        oldString: ProjectReference Include
        oldStringWin: ProjectReference Include
        newString: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        newStringWin: ProjectReference SetConfiguration=\"Configuration=Release-Dynamic\" Include 
        showFileContent: true 
    - name: build csharp swig
      working-directory: .
      run: |
        set /P SWIG_PATH=<swig_path.txt
        set PATH=%PATH%;%SWIG_PATH% 
        cd pjsip/pjsip-apps/build
        msbuild swig_csharp_pjsua2.vcxproj /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: pjsua2.dll
        path: ${{ github.workspace }}/pjsip/pjsip-apps/src/swig/csharp